#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MvvmZeroTestApp.Droid.Resource", IsApplication=true)]

namespace MvvmZeroTestApp.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.1.99.65")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Essentials.Resource.Color.browser_actions_bg_grey = global::MvvmZeroTestApp.Droid.Resource.Color.browser_actions_bg_grey;
			global::Xamarin.Essentials.Resource.Color.browser_actions_divider_color = global::MvvmZeroTestApp.Droid.Resource.Color.browser_actions_divider_color;
			global::Xamarin.Essentials.Resource.Color.browser_actions_text_color = global::MvvmZeroTestApp.Droid.Resource.Color.browser_actions_text_color;
			global::Xamarin.Essentials.Resource.Color.browser_actions_title_color = global::MvvmZeroTestApp.Droid.Resource.Color.browser_actions_title_color;
			global::Xamarin.Essentials.Resource.Dimension.browser_actions_context_menu_max_width = global::MvvmZeroTestApp.Droid.Resource.Dimension.browser_actions_context_menu_max_width;
			global::Xamarin.Essentials.Resource.Dimension.browser_actions_context_menu_min_padding = global::MvvmZeroTestApp.Droid.Resource.Dimension.browser_actions_context_menu_min_padding;
			global::Xamarin.Essentials.Resource.Id.action_divider = global::MvvmZeroTestApp.Droid.Resource.Id.action_divider;
			global::Xamarin.Essentials.Resource.Id.browser_actions_header_text = global::MvvmZeroTestApp.Droid.Resource.Id.browser_actions_header_text;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_items = global::MvvmZeroTestApp.Droid.Resource.Id.browser_actions_menu_items;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_item_icon = global::MvvmZeroTestApp.Droid.Resource.Id.browser_actions_menu_item_icon;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_item_text = global::MvvmZeroTestApp.Droid.Resource.Id.browser_actions_menu_item_text;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_view = global::MvvmZeroTestApp.Droid.Resource.Id.browser_actions_menu_view;
			global::Xamarin.Essentials.Resource.Id.chronometer = global::MvvmZeroTestApp.Droid.Resource.Id.chronometer;
			global::Xamarin.Essentials.Resource.Id.icon = global::MvvmZeroTestApp.Droid.Resource.Id.icon;
			global::Xamarin.Essentials.Resource.Id.info = global::MvvmZeroTestApp.Droid.Resource.Id.info;
			global::Xamarin.Essentials.Resource.Id.line1 = global::MvvmZeroTestApp.Droid.Resource.Id.line1;
			global::Xamarin.Essentials.Resource.Id.line3 = global::MvvmZeroTestApp.Droid.Resource.Id.line3;
			global::Xamarin.Essentials.Resource.Id.notification_main_column = global::MvvmZeroTestApp.Droid.Resource.Id.notification_main_column;
			global::Xamarin.Essentials.Resource.Id.notification_main_column_container = global::MvvmZeroTestApp.Droid.Resource.Id.notification_main_column_container;
			global::Xamarin.Essentials.Resource.Id.right_side = global::MvvmZeroTestApp.Droid.Resource.Id.right_side;
			global::Xamarin.Essentials.Resource.Id.text = global::MvvmZeroTestApp.Droid.Resource.Id.text;
			global::Xamarin.Essentials.Resource.Id.text2 = global::MvvmZeroTestApp.Droid.Resource.Id.text2;
			global::Xamarin.Essentials.Resource.Id.time = global::MvvmZeroTestApp.Droid.Resource.Id.time;
			global::Xamarin.Essentials.Resource.Id.title = global::MvvmZeroTestApp.Droid.Resource.Id.title;
			global::Xamarin.Essentials.Resource.Layout.browser_actions_context_menu_page = global::MvvmZeroTestApp.Droid.Resource.Layout.browser_actions_context_menu_page;
			global::Xamarin.Essentials.Resource.Layout.browser_actions_context_menu_row = global::MvvmZeroTestApp.Droid.Resource.Layout.browser_actions_context_menu_row;
			global::Xamarin.Essentials.Resource.String.copy_toast_msg = global::MvvmZeroTestApp.Droid.Resource.String.copy_toast_msg;
			global::Xamarin.Essentials.Resource.String.fallback_menu_item_copy_link = global::MvvmZeroTestApp.Droid.Resource.String.fallback_menu_item_copy_link;
			global::Xamarin.Essentials.Resource.String.fallback_menu_item_open_in_browser = global::MvvmZeroTestApp.Droid.Resource.String.fallback_menu_item_open_in_browser;
			global::Xamarin.Essentials.Resource.String.fallback_menu_item_share_link = global::MvvmZeroTestApp.Droid.Resource.String.fallback_menu_item_share_link;
			global::Xamarin.Essentials.Resource.Xml.image_share_filepaths = global::MvvmZeroTestApp.Droid.Resource.Xml.image_share_filepaths;
			global::Xamarin.Forms.Material.Android.Resource.Animation.nav_default_enter_anim = global::MvvmZeroTestApp.Droid.Resource.Animation.nav_default_enter_anim;
			global::Xamarin.Forms.Material.Android.Resource.Animation.nav_default_exit_anim = global::MvvmZeroTestApp.Droid.Resource.Animation.nav_default_exit_anim;
			global::Xamarin.Forms.Material.Android.Resource.Animation.nav_default_pop_enter_anim = global::MvvmZeroTestApp.Droid.Resource.Animation.nav_default_pop_enter_anim;
			global::Xamarin.Forms.Material.Android.Resource.Animation.nav_default_pop_exit_anim = global::MvvmZeroTestApp.Droid.Resource.Animation.nav_default_pop_exit_anim;
			global::Xamarin.Forms.Material.Android.Resource.Animator.nav_default_enter_anim = global::MvvmZeroTestApp.Droid.Resource.Animator.nav_default_enter_anim;
			global::Xamarin.Forms.Material.Android.Resource.Animator.nav_default_exit_anim = global::MvvmZeroTestApp.Droid.Resource.Animator.nav_default_exit_anim;
			global::Xamarin.Forms.Material.Android.Resource.Animator.nav_default_pop_enter_anim = global::MvvmZeroTestApp.Droid.Resource.Animator.nav_default_pop_enter_anim;
			global::Xamarin.Forms.Material.Android.Resource.Animator.nav_default_pop_exit_anim = global::MvvmZeroTestApp.Droid.Resource.Animator.nav_default_pop_exit_anim;
			global::Xamarin.Forms.Material.Android.Resource.Attribute.action = global::MvvmZeroTestApp.Droid.Resource.Attribute.action;
			global::Xamarin.Forms.Material.Android.Resource.Attribute.data = global::MvvmZeroTestApp.Droid.Resource.Attribute.data;
			global::Xamarin.Forms.Material.Android.Resource.Attribute.dataPattern = global::MvvmZeroTestApp.Droid.Resource.Attribute.dataPattern;
			global::Xamarin.Forms.Material.Android.Resource.Attribute.graph = global::MvvmZeroTestApp.Droid.Resource.Attribute.graph;
			global::Xamarin.Forms.Material.Android.Resource.Attribute.navGraph = global::MvvmZeroTestApp.Droid.Resource.Attribute.navGraph;
			global::Xamarin.Forms.Material.Android.Resource.Attribute.targetPackage = global::MvvmZeroTestApp.Droid.Resource.Attribute.targetPackage;
			global::Xamarin.Forms.Material.Android.Resource.Color.notification_material_background_media_default_color = global::MvvmZeroTestApp.Droid.Resource.Color.notification_material_background_media_default_color;
			global::Xamarin.Forms.Material.Android.Resource.Color.primary_text_default_material_dark = global::MvvmZeroTestApp.Droid.Resource.Color.primary_text_default_material_dark;
			global::Xamarin.Forms.Material.Android.Resource.Color.secondary_text_default_material_dark = global::MvvmZeroTestApp.Droid.Resource.Color.secondary_text_default_material_dark;
			global::Xamarin.Forms.Material.Android.Resource.Id.action0 = global::MvvmZeroTestApp.Droid.Resource.Id.action0;
			global::Xamarin.Forms.Material.Android.Resource.Id.action_divider = global::MvvmZeroTestApp.Droid.Resource.Id.action_divider;
			global::Xamarin.Forms.Material.Android.Resource.Id.cancel_action = global::MvvmZeroTestApp.Droid.Resource.Id.cancel_action;
			global::Xamarin.Forms.Material.Android.Resource.Id.chronometer = global::MvvmZeroTestApp.Droid.Resource.Id.chronometer;
			global::Xamarin.Forms.Material.Android.Resource.Id.end_padder = global::MvvmZeroTestApp.Droid.Resource.Id.end_padder;
			global::Xamarin.Forms.Material.Android.Resource.Id.icon = global::MvvmZeroTestApp.Droid.Resource.Id.icon;
			global::Xamarin.Forms.Material.Android.Resource.Id.info = global::MvvmZeroTestApp.Droid.Resource.Id.info;
			global::Xamarin.Forms.Material.Android.Resource.Id.line1 = global::MvvmZeroTestApp.Droid.Resource.Id.line1;
			global::Xamarin.Forms.Material.Android.Resource.Id.line3 = global::MvvmZeroTestApp.Droid.Resource.Id.line3;
			global::Xamarin.Forms.Material.Android.Resource.Id.media_actions = global::MvvmZeroTestApp.Droid.Resource.Id.media_actions;
			global::Xamarin.Forms.Material.Android.Resource.Id.media_controller_compat_view_tag = global::MvvmZeroTestApp.Droid.Resource.Id.media_controller_compat_view_tag;
			global::Xamarin.Forms.Material.Android.Resource.Id.nav_controller_view_tag = global::MvvmZeroTestApp.Droid.Resource.Id.nav_controller_view_tag;
			global::Xamarin.Forms.Material.Android.Resource.Id.notification_main_column = global::MvvmZeroTestApp.Droid.Resource.Id.notification_main_column;
			global::Xamarin.Forms.Material.Android.Resource.Id.notification_main_column_container = global::MvvmZeroTestApp.Droid.Resource.Id.notification_main_column_container;
			global::Xamarin.Forms.Material.Android.Resource.Id.right_side = global::MvvmZeroTestApp.Droid.Resource.Id.right_side;
			global::Xamarin.Forms.Material.Android.Resource.Id.sliding_tabs = global::MvvmZeroTestApp.Droid.Resource.Id.sliding_tabs;
			global::Xamarin.Forms.Material.Android.Resource.Id.status_bar_latest_event_content = global::MvvmZeroTestApp.Droid.Resource.Id.status_bar_latest_event_content;
			global::Xamarin.Forms.Material.Android.Resource.Id.text = global::MvvmZeroTestApp.Droid.Resource.Id.text;
			global::Xamarin.Forms.Material.Android.Resource.Id.text2 = global::MvvmZeroTestApp.Droid.Resource.Id.text2;
			global::Xamarin.Forms.Material.Android.Resource.Id.time = global::MvvmZeroTestApp.Droid.Resource.Id.time;
			global::Xamarin.Forms.Material.Android.Resource.Id.title = global::MvvmZeroTestApp.Droid.Resource.Id.title;
			global::Xamarin.Forms.Material.Android.Resource.Id.toolbar = global::MvvmZeroTestApp.Droid.Resource.Id.toolbar;
			global::Xamarin.Forms.Material.Android.Resource.Integer.cancel_button_image_alpha = global::MvvmZeroTestApp.Droid.Resource.Integer.cancel_button_image_alpha;
			global::Xamarin.Forms.Material.Android.Resource.Integer.config_navAnimTime = global::MvvmZeroTestApp.Droid.Resource.Integer.config_navAnimTime;
			global::Xamarin.Forms.Material.Android.Resource.Layout.notification_media_action = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_media_action;
			global::Xamarin.Forms.Material.Android.Resource.Layout.notification_media_cancel_action = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_media_cancel_action;
			global::Xamarin.Forms.Material.Android.Resource.Layout.notification_template_big_media = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_template_big_media;
			global::Xamarin.Forms.Material.Android.Resource.Layout.notification_template_big_media_custom = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_template_big_media_custom;
			global::Xamarin.Forms.Material.Android.Resource.Layout.notification_template_big_media_narrow = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_template_big_media_narrow;
			global::Xamarin.Forms.Material.Android.Resource.Layout.notification_template_big_media_narrow_custom = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_template_big_media_narrow_custom;
			global::Xamarin.Forms.Material.Android.Resource.Layout.notification_template_lines_media = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_template_lines_media;
			global::Xamarin.Forms.Material.Android.Resource.Layout.notification_template_media = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_template_media;
			global::Xamarin.Forms.Material.Android.Resource.Layout.notification_template_media_custom = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_template_media_custom;
			global::Xamarin.Forms.Material.Android.Resource.Layout.Tabbar = global::MvvmZeroTestApp.Droid.Resource.Layout.Tabbar;
			global::Xamarin.Forms.Material.Android.Resource.Layout.Toolbar = global::MvvmZeroTestApp.Droid.Resource.Layout.Toolbar;
			global::Xamarin.Forms.Material.Android.Resource.String.nav_app_bar_navigate_up_description = global::MvvmZeroTestApp.Droid.Resource.String.nav_app_bar_navigate_up_description;
			global::Xamarin.Forms.Material.Android.Resource.String.nav_app_bar_open_drawer_description = global::MvvmZeroTestApp.Droid.Resource.String.nav_app_bar_open_drawer_description;
			global::Xamarin.Forms.Material.Android.Resource.Style.AppCompatDialogStyle = global::MvvmZeroTestApp.Droid.Resource.Style.AppCompatDialogStyle;
			global::Xamarin.Forms.Material.Android.Resource.Style.MainTheme = global::MvvmZeroTestApp.Droid.Resource.Style.MainTheme;
			global::Xamarin.Forms.Material.Android.Resource.Style.MainTheme_Base = global::MvvmZeroTestApp.Droid.Resource.Style.MainTheme_Base;
			global::Xamarin.Forms.Material.Android.Resource.Style.TextAppearance_Compat_Notification_Info_Media = global::MvvmZeroTestApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Info_Media;
			global::Xamarin.Forms.Material.Android.Resource.Style.TextAppearance_Compat_Notification_Line2_Media = global::MvvmZeroTestApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Line2_Media;
			global::Xamarin.Forms.Material.Android.Resource.Style.TextAppearance_Compat_Notification_Media = global::MvvmZeroTestApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Media;
			global::Xamarin.Forms.Material.Android.Resource.Style.TextAppearance_Compat_Notification_Time_Media = global::MvvmZeroTestApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Time_Media;
			global::Xamarin.Forms.Material.Android.Resource.Style.TextAppearance_Compat_Notification_Title_Media = global::MvvmZeroTestApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Title_Media;
			global::Xamarin.Forms.Material.Android.Resource.Styleable.ActivityNavigator = global::MvvmZeroTestApp.Droid.Resource.Styleable.ActivityNavigator;
			global::Xamarin.Forms.Material.Android.Resource.Styleable.ActivityNavigator_action = global::MvvmZeroTestApp.Droid.Resource.Styleable.ActivityNavigator_action;
			global::Xamarin.Forms.Material.Android.Resource.Styleable.ActivityNavigator_android_name = global::MvvmZeroTestApp.Droid.Resource.Styleable.ActivityNavigator_android_name;
			global::Xamarin.Forms.Material.Android.Resource.Styleable.ActivityNavigator_data = global::MvvmZeroTestApp.Droid.Resource.Styleable.ActivityNavigator_data;
			global::Xamarin.Forms.Material.Android.Resource.Styleable.ActivityNavigator_dataPattern = global::MvvmZeroTestApp.Droid.Resource.Styleable.ActivityNavigator_dataPattern;
			global::Xamarin.Forms.Material.Android.Resource.Styleable.ActivityNavigator_targetPackage = global::MvvmZeroTestApp.Droid.Resource.Styleable.ActivityNavigator_targetPackage;
			global::Xamarin.Forms.Material.Android.Resource.Styleable.NavHost = global::MvvmZeroTestApp.Droid.Resource.Styleable.NavHost;
			global::Xamarin.Forms.Material.Android.Resource.Styleable.NavHost_navGraph = global::MvvmZeroTestApp.Droid.Resource.Styleable.NavHost_navGraph;
			global::Xamarin.Forms.Material.Android.Resource.Styleable.NavInclude = global::MvvmZeroTestApp.Droid.Resource.Styleable.NavInclude;
			global::Xamarin.Forms.Material.Android.Resource.Styleable.NavInclude_graph = global::MvvmZeroTestApp.Droid.Resource.Styleable.NavInclude_graph;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.nav_default_enter_anim = global::MvvmZeroTestApp.Droid.Resource.Animation.nav_default_enter_anim;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.nav_default_exit_anim = global::MvvmZeroTestApp.Droid.Resource.Animation.nav_default_exit_anim;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.nav_default_pop_enter_anim = global::MvvmZeroTestApp.Droid.Resource.Animation.nav_default_pop_enter_anim;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.nav_default_pop_exit_anim = global::MvvmZeroTestApp.Droid.Resource.Animation.nav_default_pop_exit_anim;
			global::Xamarin.Forms.Platform.Android.Resource.Animator.nav_default_enter_anim = global::MvvmZeroTestApp.Droid.Resource.Animator.nav_default_enter_anim;
			global::Xamarin.Forms.Platform.Android.Resource.Animator.nav_default_exit_anim = global::MvvmZeroTestApp.Droid.Resource.Animator.nav_default_exit_anim;
			global::Xamarin.Forms.Platform.Android.Resource.Animator.nav_default_pop_enter_anim = global::MvvmZeroTestApp.Droid.Resource.Animator.nav_default_pop_enter_anim;
			global::Xamarin.Forms.Platform.Android.Resource.Animator.nav_default_pop_exit_anim = global::MvvmZeroTestApp.Droid.Resource.Animator.nav_default_pop_exit_anim;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.action = global::MvvmZeroTestApp.Droid.Resource.Attribute.action;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.data = global::MvvmZeroTestApp.Droid.Resource.Attribute.data;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.dataPattern = global::MvvmZeroTestApp.Droid.Resource.Attribute.dataPattern;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.graph = global::MvvmZeroTestApp.Droid.Resource.Attribute.graph;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.navGraph = global::MvvmZeroTestApp.Droid.Resource.Attribute.navGraph;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.targetPackage = global::MvvmZeroTestApp.Droid.Resource.Attribute.targetPackage;
			global::Xamarin.Forms.Platform.Android.Resource.Color.notification_material_background_media_default_color = global::MvvmZeroTestApp.Droid.Resource.Color.notification_material_background_media_default_color;
			global::Xamarin.Forms.Platform.Android.Resource.Color.primary_text_default_material_dark = global::MvvmZeroTestApp.Droid.Resource.Color.primary_text_default_material_dark;
			global::Xamarin.Forms.Platform.Android.Resource.Color.secondary_text_default_material_dark = global::MvvmZeroTestApp.Droid.Resource.Color.secondary_text_default_material_dark;
			global::Xamarin.Forms.Platform.Android.Resource.Id.action0 = global::MvvmZeroTestApp.Droid.Resource.Id.action0;
			global::Xamarin.Forms.Platform.Android.Resource.Id.action_divider = global::MvvmZeroTestApp.Droid.Resource.Id.action_divider;
			global::Xamarin.Forms.Platform.Android.Resource.Id.cancel_action = global::MvvmZeroTestApp.Droid.Resource.Id.cancel_action;
			global::Xamarin.Forms.Platform.Android.Resource.Id.chronometer = global::MvvmZeroTestApp.Droid.Resource.Id.chronometer;
			global::Xamarin.Forms.Platform.Android.Resource.Id.end_padder = global::MvvmZeroTestApp.Droid.Resource.Id.end_padder;
			global::Xamarin.Forms.Platform.Android.Resource.Id.icon = global::MvvmZeroTestApp.Droid.Resource.Id.icon;
			global::Xamarin.Forms.Platform.Android.Resource.Id.info = global::MvvmZeroTestApp.Droid.Resource.Id.info;
			global::Xamarin.Forms.Platform.Android.Resource.Id.line1 = global::MvvmZeroTestApp.Droid.Resource.Id.line1;
			global::Xamarin.Forms.Platform.Android.Resource.Id.line3 = global::MvvmZeroTestApp.Droid.Resource.Id.line3;
			global::Xamarin.Forms.Platform.Android.Resource.Id.media_actions = global::MvvmZeroTestApp.Droid.Resource.Id.media_actions;
			global::Xamarin.Forms.Platform.Android.Resource.Id.media_controller_compat_view_tag = global::MvvmZeroTestApp.Droid.Resource.Id.media_controller_compat_view_tag;
			global::Xamarin.Forms.Platform.Android.Resource.Id.nav_controller_view_tag = global::MvvmZeroTestApp.Droid.Resource.Id.nav_controller_view_tag;
			global::Xamarin.Forms.Platform.Android.Resource.Id.notification_main_column = global::MvvmZeroTestApp.Droid.Resource.Id.notification_main_column;
			global::Xamarin.Forms.Platform.Android.Resource.Id.notification_main_column_container = global::MvvmZeroTestApp.Droid.Resource.Id.notification_main_column_container;
			global::Xamarin.Forms.Platform.Android.Resource.Id.right_side = global::MvvmZeroTestApp.Droid.Resource.Id.right_side;
			global::Xamarin.Forms.Platform.Android.Resource.Id.sliding_tabs = global::MvvmZeroTestApp.Droid.Resource.Id.sliding_tabs;
			global::Xamarin.Forms.Platform.Android.Resource.Id.status_bar_latest_event_content = global::MvvmZeroTestApp.Droid.Resource.Id.status_bar_latest_event_content;
			global::Xamarin.Forms.Platform.Android.Resource.Id.text = global::MvvmZeroTestApp.Droid.Resource.Id.text;
			global::Xamarin.Forms.Platform.Android.Resource.Id.text2 = global::MvvmZeroTestApp.Droid.Resource.Id.text2;
			global::Xamarin.Forms.Platform.Android.Resource.Id.time = global::MvvmZeroTestApp.Droid.Resource.Id.time;
			global::Xamarin.Forms.Platform.Android.Resource.Id.title = global::MvvmZeroTestApp.Droid.Resource.Id.title;
			global::Xamarin.Forms.Platform.Android.Resource.Id.toolbar = global::MvvmZeroTestApp.Droid.Resource.Id.toolbar;
			global::Xamarin.Forms.Platform.Android.Resource.Integer.cancel_button_image_alpha = global::MvvmZeroTestApp.Droid.Resource.Integer.cancel_button_image_alpha;
			global::Xamarin.Forms.Platform.Android.Resource.Integer.config_navAnimTime = global::MvvmZeroTestApp.Droid.Resource.Integer.config_navAnimTime;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_media_action = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_media_action;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_media_cancel_action = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_media_cancel_action;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_template_big_media = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_template_big_media;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_template_big_media_custom = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_template_big_media_custom;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_template_big_media_narrow = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_template_big_media_narrow;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_template_big_media_narrow_custom = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_template_big_media_narrow_custom;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_template_lines_media = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_template_lines_media;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_template_media = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_template_media;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_template_media_custom = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_template_media_custom;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.Tabbar = global::MvvmZeroTestApp.Droid.Resource.Layout.Tabbar;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.Toolbar = global::MvvmZeroTestApp.Droid.Resource.Layout.Toolbar;
			global::Xamarin.Forms.Platform.Android.Resource.String.nav_app_bar_navigate_up_description = global::MvvmZeroTestApp.Droid.Resource.String.nav_app_bar_navigate_up_description;
			global::Xamarin.Forms.Platform.Android.Resource.String.nav_app_bar_open_drawer_description = global::MvvmZeroTestApp.Droid.Resource.String.nav_app_bar_open_drawer_description;
			global::Xamarin.Forms.Platform.Android.Resource.Style.AppCompatDialogStyle = global::MvvmZeroTestApp.Droid.Resource.Style.AppCompatDialogStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Style.MainTheme = global::MvvmZeroTestApp.Droid.Resource.Style.MainTheme;
			global::Xamarin.Forms.Platform.Android.Resource.Style.MainTheme_Base = global::MvvmZeroTestApp.Droid.Resource.Style.MainTheme_Base;
			global::Xamarin.Forms.Platform.Android.Resource.Style.TextAppearance_Compat_Notification_Info_Media = global::MvvmZeroTestApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Info_Media;
			global::Xamarin.Forms.Platform.Android.Resource.Style.TextAppearance_Compat_Notification_Line2_Media = global::MvvmZeroTestApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Line2_Media;
			global::Xamarin.Forms.Platform.Android.Resource.Style.TextAppearance_Compat_Notification_Media = global::MvvmZeroTestApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Media;
			global::Xamarin.Forms.Platform.Android.Resource.Style.TextAppearance_Compat_Notification_Time_Media = global::MvvmZeroTestApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Time_Media;
			global::Xamarin.Forms.Platform.Android.Resource.Style.TextAppearance_Compat_Notification_Title_Media = global::MvvmZeroTestApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Title_Media;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.ActivityNavigator = global::MvvmZeroTestApp.Droid.Resource.Styleable.ActivityNavigator;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.ActivityNavigator_action = global::MvvmZeroTestApp.Droid.Resource.Styleable.ActivityNavigator_action;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.ActivityNavigator_android_name = global::MvvmZeroTestApp.Droid.Resource.Styleable.ActivityNavigator_android_name;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.ActivityNavigator_data = global::MvvmZeroTestApp.Droid.Resource.Styleable.ActivityNavigator_data;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.ActivityNavigator_dataPattern = global::MvvmZeroTestApp.Droid.Resource.Styleable.ActivityNavigator_dataPattern;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.ActivityNavigator_targetPackage = global::MvvmZeroTestApp.Droid.Resource.Styleable.ActivityNavigator_targetPackage;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.NavHost = global::MvvmZeroTestApp.Droid.Resource.Styleable.NavHost;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.NavHost_navGraph = global::MvvmZeroTestApp.Droid.Resource.Styleable.NavHost_navGraph;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.NavInclude = global::MvvmZeroTestApp.Droid.Resource.Styleable.NavInclude;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.NavInclude_graph = global::MvvmZeroTestApp.Droid.Resource.Styleable.NavInclude_graph;
			global::Xamarin.Forms.Platform.Resource.Animation.nav_default_enter_anim = global::MvvmZeroTestApp.Droid.Resource.Animation.nav_default_enter_anim;
			global::Xamarin.Forms.Platform.Resource.Animation.nav_default_exit_anim = global::MvvmZeroTestApp.Droid.Resource.Animation.nav_default_exit_anim;
			global::Xamarin.Forms.Platform.Resource.Animation.nav_default_pop_enter_anim = global::MvvmZeroTestApp.Droid.Resource.Animation.nav_default_pop_enter_anim;
			global::Xamarin.Forms.Platform.Resource.Animation.nav_default_pop_exit_anim = global::MvvmZeroTestApp.Droid.Resource.Animation.nav_default_pop_exit_anim;
			global::Xamarin.Forms.Platform.Resource.Animator.nav_default_enter_anim = global::MvvmZeroTestApp.Droid.Resource.Animator.nav_default_enter_anim;
			global::Xamarin.Forms.Platform.Resource.Animator.nav_default_exit_anim = global::MvvmZeroTestApp.Droid.Resource.Animator.nav_default_exit_anim;
			global::Xamarin.Forms.Platform.Resource.Animator.nav_default_pop_enter_anim = global::MvvmZeroTestApp.Droid.Resource.Animator.nav_default_pop_enter_anim;
			global::Xamarin.Forms.Platform.Resource.Animator.nav_default_pop_exit_anim = global::MvvmZeroTestApp.Droid.Resource.Animator.nav_default_pop_exit_anim;
			global::Xamarin.Forms.Platform.Resource.Attribute.action = global::MvvmZeroTestApp.Droid.Resource.Attribute.action;
			global::Xamarin.Forms.Platform.Resource.Attribute.data = global::MvvmZeroTestApp.Droid.Resource.Attribute.data;
			global::Xamarin.Forms.Platform.Resource.Attribute.dataPattern = global::MvvmZeroTestApp.Droid.Resource.Attribute.dataPattern;
			global::Xamarin.Forms.Platform.Resource.Attribute.graph = global::MvvmZeroTestApp.Droid.Resource.Attribute.graph;
			global::Xamarin.Forms.Platform.Resource.Attribute.navGraph = global::MvvmZeroTestApp.Droid.Resource.Attribute.navGraph;
			global::Xamarin.Forms.Platform.Resource.Attribute.targetPackage = global::MvvmZeroTestApp.Droid.Resource.Attribute.targetPackage;
			global::Xamarin.Forms.Platform.Resource.Color.notification_material_background_media_default_color = global::MvvmZeroTestApp.Droid.Resource.Color.notification_material_background_media_default_color;
			global::Xamarin.Forms.Platform.Resource.Color.primary_text_default_material_dark = global::MvvmZeroTestApp.Droid.Resource.Color.primary_text_default_material_dark;
			global::Xamarin.Forms.Platform.Resource.Color.secondary_text_default_material_dark = global::MvvmZeroTestApp.Droid.Resource.Color.secondary_text_default_material_dark;
			global::Xamarin.Forms.Platform.Resource.Id.action0 = global::MvvmZeroTestApp.Droid.Resource.Id.action0;
			global::Xamarin.Forms.Platform.Resource.Id.action_divider = global::MvvmZeroTestApp.Droid.Resource.Id.action_divider;
			global::Xamarin.Forms.Platform.Resource.Id.cancel_action = global::MvvmZeroTestApp.Droid.Resource.Id.cancel_action;
			global::Xamarin.Forms.Platform.Resource.Id.chronometer = global::MvvmZeroTestApp.Droid.Resource.Id.chronometer;
			global::Xamarin.Forms.Platform.Resource.Id.end_padder = global::MvvmZeroTestApp.Droid.Resource.Id.end_padder;
			global::Xamarin.Forms.Platform.Resource.Id.icon = global::MvvmZeroTestApp.Droid.Resource.Id.icon;
			global::Xamarin.Forms.Platform.Resource.Id.info = global::MvvmZeroTestApp.Droid.Resource.Id.info;
			global::Xamarin.Forms.Platform.Resource.Id.line1 = global::MvvmZeroTestApp.Droid.Resource.Id.line1;
			global::Xamarin.Forms.Platform.Resource.Id.line3 = global::MvvmZeroTestApp.Droid.Resource.Id.line3;
			global::Xamarin.Forms.Platform.Resource.Id.media_actions = global::MvvmZeroTestApp.Droid.Resource.Id.media_actions;
			global::Xamarin.Forms.Platform.Resource.Id.media_controller_compat_view_tag = global::MvvmZeroTestApp.Droid.Resource.Id.media_controller_compat_view_tag;
			global::Xamarin.Forms.Platform.Resource.Id.nav_controller_view_tag = global::MvvmZeroTestApp.Droid.Resource.Id.nav_controller_view_tag;
			global::Xamarin.Forms.Platform.Resource.Id.notification_main_column = global::MvvmZeroTestApp.Droid.Resource.Id.notification_main_column;
			global::Xamarin.Forms.Platform.Resource.Id.notification_main_column_container = global::MvvmZeroTestApp.Droid.Resource.Id.notification_main_column_container;
			global::Xamarin.Forms.Platform.Resource.Id.right_side = global::MvvmZeroTestApp.Droid.Resource.Id.right_side;
			global::Xamarin.Forms.Platform.Resource.Id.sliding_tabs = global::MvvmZeroTestApp.Droid.Resource.Id.sliding_tabs;
			global::Xamarin.Forms.Platform.Resource.Id.status_bar_latest_event_content = global::MvvmZeroTestApp.Droid.Resource.Id.status_bar_latest_event_content;
			global::Xamarin.Forms.Platform.Resource.Id.text = global::MvvmZeroTestApp.Droid.Resource.Id.text;
			global::Xamarin.Forms.Platform.Resource.Id.text2 = global::MvvmZeroTestApp.Droid.Resource.Id.text2;
			global::Xamarin.Forms.Platform.Resource.Id.time = global::MvvmZeroTestApp.Droid.Resource.Id.time;
			global::Xamarin.Forms.Platform.Resource.Id.title = global::MvvmZeroTestApp.Droid.Resource.Id.title;
			global::Xamarin.Forms.Platform.Resource.Id.toolbar = global::MvvmZeroTestApp.Droid.Resource.Id.toolbar;
			global::Xamarin.Forms.Platform.Resource.Integer.cancel_button_image_alpha = global::MvvmZeroTestApp.Droid.Resource.Integer.cancel_button_image_alpha;
			global::Xamarin.Forms.Platform.Resource.Integer.config_navAnimTime = global::MvvmZeroTestApp.Droid.Resource.Integer.config_navAnimTime;
			global::Xamarin.Forms.Platform.Resource.Layout.notification_media_action = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_media_action;
			global::Xamarin.Forms.Platform.Resource.Layout.notification_media_cancel_action = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_media_cancel_action;
			global::Xamarin.Forms.Platform.Resource.Layout.notification_template_big_media = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_template_big_media;
			global::Xamarin.Forms.Platform.Resource.Layout.notification_template_big_media_custom = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_template_big_media_custom;
			global::Xamarin.Forms.Platform.Resource.Layout.notification_template_big_media_narrow = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_template_big_media_narrow;
			global::Xamarin.Forms.Platform.Resource.Layout.notification_template_big_media_narrow_custom = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_template_big_media_narrow_custom;
			global::Xamarin.Forms.Platform.Resource.Layout.notification_template_lines_media = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_template_lines_media;
			global::Xamarin.Forms.Platform.Resource.Layout.notification_template_media = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_template_media;
			global::Xamarin.Forms.Platform.Resource.Layout.notification_template_media_custom = global::MvvmZeroTestApp.Droid.Resource.Layout.notification_template_media_custom;
			global::Xamarin.Forms.Platform.Resource.Layout.Tabbar = global::MvvmZeroTestApp.Droid.Resource.Layout.Tabbar;
			global::Xamarin.Forms.Platform.Resource.Layout.Toolbar = global::MvvmZeroTestApp.Droid.Resource.Layout.Toolbar;
			global::Xamarin.Forms.Platform.Resource.String.nav_app_bar_navigate_up_description = global::MvvmZeroTestApp.Droid.Resource.String.nav_app_bar_navigate_up_description;
			global::Xamarin.Forms.Platform.Resource.String.nav_app_bar_open_drawer_description = global::MvvmZeroTestApp.Droid.Resource.String.nav_app_bar_open_drawer_description;
			global::Xamarin.Forms.Platform.Resource.Style.AppCompatDialogStyle = global::MvvmZeroTestApp.Droid.Resource.Style.AppCompatDialogStyle;
			global::Xamarin.Forms.Platform.Resource.Style.MainTheme = global::MvvmZeroTestApp.Droid.Resource.Style.MainTheme;
			global::Xamarin.Forms.Platform.Resource.Style.MainTheme_Base = global::MvvmZeroTestApp.Droid.Resource.Style.MainTheme_Base;
			global::Xamarin.Forms.Platform.Resource.Style.TextAppearance_Compat_Notification_Info_Media = global::MvvmZeroTestApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Info_Media;
			global::Xamarin.Forms.Platform.Resource.Style.TextAppearance_Compat_Notification_Line2_Media = global::MvvmZeroTestApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Line2_Media;
			global::Xamarin.Forms.Platform.Resource.Style.TextAppearance_Compat_Notification_Media = global::MvvmZeroTestApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Media;
			global::Xamarin.Forms.Platform.Resource.Style.TextAppearance_Compat_Notification_Time_Media = global::MvvmZeroTestApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Time_Media;
			global::Xamarin.Forms.Platform.Resource.Style.TextAppearance_Compat_Notification_Title_Media = global::MvvmZeroTestApp.Droid.Resource.Style.TextAppearance_Compat_Notification_Title_Media;
			global::Xamarin.Forms.Platform.Resource.Styleable.ActivityNavigator = global::MvvmZeroTestApp.Droid.Resource.Styleable.ActivityNavigator;
			global::Xamarin.Forms.Platform.Resource.Styleable.ActivityNavigator_action = global::MvvmZeroTestApp.Droid.Resource.Styleable.ActivityNavigator_action;
			global::Xamarin.Forms.Platform.Resource.Styleable.ActivityNavigator_android_name = global::MvvmZeroTestApp.Droid.Resource.Styleable.ActivityNavigator_android_name;
			global::Xamarin.Forms.Platform.Resource.Styleable.ActivityNavigator_data = global::MvvmZeroTestApp.Droid.Resource.Styleable.ActivityNavigator_data;
			global::Xamarin.Forms.Platform.Resource.Styleable.ActivityNavigator_dataPattern = global::MvvmZeroTestApp.Droid.Resource.Styleable.ActivityNavigator_dataPattern;
			global::Xamarin.Forms.Platform.Resource.Styleable.ActivityNavigator_targetPackage = global::MvvmZeroTestApp.Droid.Resource.Styleable.ActivityNavigator_targetPackage;
			global::Xamarin.Forms.Platform.Resource.Styleable.NavHost = global::MvvmZeroTestApp.Droid.Resource.Styleable.NavHost;
			global::Xamarin.Forms.Platform.Resource.Styleable.NavHost_navGraph = global::MvvmZeroTestApp.Droid.Resource.Styleable.NavHost_navGraph;
			global::Xamarin.Forms.Platform.Resource.Styleable.NavInclude = global::MvvmZeroTestApp.Droid.Resource.Styleable.NavInclude;
			global::Xamarin.Forms.Platform.Resource.Styleable.NavInclude_graph = global::MvvmZeroTestApp.Droid.Resource.Styleable.NavInclude_graph;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int nav_default_enter_anim = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int nav_default_exit_anim = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int nav_default_pop_enter_anim = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int nav_default_pop_exit_anim = 2130771971;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7F020000
			public const int nav_default_enter_anim = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int nav_default_exit_anim = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int nav_default_pop_enter_anim = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int nav_default_pop_exit_anim = 2130837507;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F030000
			public const int action = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int data = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int dataPattern = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int externalRouteEnabledDrawable = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int externalRouteEnabledDrawableStatic = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int graph = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int mediaRouteAudioTrackDrawable = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int mediaRouteBodyTextAppearance = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int mediaRouteButtonStyle = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int mediaRouteButtonTint = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int mediaRouteCloseDrawable = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int mediaRouteControlPanelThemeOverlay = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int mediaRouteDefaultIconDrawable = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int mediaRouteDividerColor = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int mediaRouteHeaderTextAppearance = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int mediaRoutePauseDrawable = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int mediaRoutePlayDrawable = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int mediaRouteSpeakerGroupIconDrawable = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int mediaRouteSpeakerIconDrawable = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int mediaRouteStopDrawable = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int mediaRouteTheme = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int mediaRouteTvIconDrawable = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int navGraph = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int targetPackage = 2130903063;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7F040000
			public const int is_tablet = 2130968576;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F050000
			public const int browser_actions_bg_grey = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int browser_actions_divider_color = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int browser_actions_text_color = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int browser_actions_title_color = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int colorAccent = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int colorPrimary = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int colorPrimaryDark = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int launcher_background = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int mr_cast_meta_black_scrim = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int mr_cast_meta_default_background = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int mr_cast_meta_default_text_color = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int mr_cast_progressbar_background_dark = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int mr_cast_progressbar_background_light = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int mr_cast_progressbar_progress_and_thumb_dark = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int mr_cast_progressbar_progress_and_thumb_light = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int mr_cast_route_divider_dark = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int mr_cast_route_divider_light = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int mr_dynamic_dialog_background_dark = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int mr_dynamic_dialog_background_light = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int mr_dynamic_dialog_header_text_color_dark = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int mr_dynamic_dialog_header_text_color_light = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int mr_dynamic_dialog_icon_dark = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int mr_dynamic_dialog_icon_light = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int mr_dynamic_dialog_route_text_color_dark = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int mr_dynamic_dialog_route_text_color_light = 2131034136;
			
			// aapt resource value: 0x7F050019
			public const int notification_material_background_media_default_color = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int primary_text_default_material_dark = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public const int secondary_text_default_material_dark = 2131034139;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F060000
			public const int browser_actions_context_menu_max_width = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int browser_actions_context_menu_min_padding = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int mr_cast_group_volume_seekbar_height = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int mr_cast_meta_art_size = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int mr_cast_meta_subtitle_text_size = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int mr_cast_route_volume_seekbar_height = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int mr_cast_seekbar_thumb_size = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int mr_controller_volume_group_list_item_height = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int mr_controller_volume_group_list_item_icon_size = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int mr_controller_volume_group_list_max_height = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int mr_controller_volume_group_list_padding_top = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int mr_dialog_fixed_width_major = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int mr_dialog_fixed_width_minor = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int mr_dynamic_dialog_header_text_size = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int mr_dynamic_dialog_route_text_size = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int mr_dynamic_dialog_row_height = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int mr_dynamic_volume_group_list_item_height = 2131099664;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F070000
			public const int ic_audiotrack_dark = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int ic_audiotrack_light = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int ic_checked_checkbox = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int ic_dialog_close_dark = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int ic_dialog_close_light = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int ic_group_collapse_00 = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int ic_group_collapse_01 = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int ic_group_collapse_02 = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int ic_group_collapse_03 = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int ic_group_collapse_04 = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int ic_group_collapse_05 = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int ic_group_collapse_06 = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int ic_group_collapse_07 = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int ic_group_collapse_08 = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int ic_group_collapse_09 = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int ic_group_collapse_10 = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int ic_group_collapse_11 = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int ic_group_collapse_12 = 2131165201;
			
			// aapt resource value: 0x7F070012
			public const int ic_group_collapse_13 = 2131165202;
			
			// aapt resource value: 0x7F070013
			public const int ic_group_collapse_14 = 2131165203;
			
			// aapt resource value: 0x7F070014
			public const int ic_group_collapse_15 = 2131165204;
			
			// aapt resource value: 0x7F070015
			public const int ic_group_expand_00 = 2131165205;
			
			// aapt resource value: 0x7F070016
			public const int ic_group_expand_01 = 2131165206;
			
			// aapt resource value: 0x7F070017
			public const int ic_group_expand_02 = 2131165207;
			
			// aapt resource value: 0x7F070018
			public const int ic_group_expand_03 = 2131165208;
			
			// aapt resource value: 0x7F070019
			public const int ic_group_expand_04 = 2131165209;
			
			// aapt resource value: 0x7F07001A
			public const int ic_group_expand_05 = 2131165210;
			
			// aapt resource value: 0x7F07001B
			public const int ic_group_expand_06 = 2131165211;
			
			// aapt resource value: 0x7F07001C
			public const int ic_group_expand_07 = 2131165212;
			
			// aapt resource value: 0x7F07001D
			public const int ic_group_expand_08 = 2131165213;
			
			// aapt resource value: 0x7F07001E
			public const int ic_group_expand_09 = 2131165214;
			
			// aapt resource value: 0x7F07001F
			public const int ic_group_expand_10 = 2131165215;
			
			// aapt resource value: 0x7F070020
			public const int ic_group_expand_11 = 2131165216;
			
			// aapt resource value: 0x7F070021
			public const int ic_group_expand_12 = 2131165217;
			
			// aapt resource value: 0x7F070022
			public const int ic_group_expand_13 = 2131165218;
			
			// aapt resource value: 0x7F070023
			public const int ic_group_expand_14 = 2131165219;
			
			// aapt resource value: 0x7F070024
			public const int ic_group_expand_15 = 2131165220;
			
			// aapt resource value: 0x7F070025
			public const int ic_media_pause_dark = 2131165221;
			
			// aapt resource value: 0x7F070026
			public const int ic_media_pause_light = 2131165222;
			
			// aapt resource value: 0x7F070027
			public const int ic_media_play_dark = 2131165223;
			
			// aapt resource value: 0x7F070028
			public const int ic_media_play_light = 2131165224;
			
			// aapt resource value: 0x7F070029
			public const int ic_media_stop_dark = 2131165225;
			
			// aapt resource value: 0x7F07002A
			public const int ic_media_stop_light = 2131165226;
			
			// aapt resource value: 0x7F07002B
			public const int ic_mr_button_connected_00_dark = 2131165227;
			
			// aapt resource value: 0x7F07002C
			public const int ic_mr_button_connected_00_light = 2131165228;
			
			// aapt resource value: 0x7F07002D
			public const int ic_mr_button_connected_01_dark = 2131165229;
			
			// aapt resource value: 0x7F07002E
			public const int ic_mr_button_connected_01_light = 2131165230;
			
			// aapt resource value: 0x7F07002F
			public const int ic_mr_button_connected_02_dark = 2131165231;
			
			// aapt resource value: 0x7F070030
			public const int ic_mr_button_connected_02_light = 2131165232;
			
			// aapt resource value: 0x7F070031
			public const int ic_mr_button_connected_03_dark = 2131165233;
			
			// aapt resource value: 0x7F070032
			public const int ic_mr_button_connected_03_light = 2131165234;
			
			// aapt resource value: 0x7F070033
			public const int ic_mr_button_connected_04_dark = 2131165235;
			
			// aapt resource value: 0x7F070034
			public const int ic_mr_button_connected_04_light = 2131165236;
			
			// aapt resource value: 0x7F070035
			public const int ic_mr_button_connected_05_dark = 2131165237;
			
			// aapt resource value: 0x7F070036
			public const int ic_mr_button_connected_05_light = 2131165238;
			
			// aapt resource value: 0x7F070037
			public const int ic_mr_button_connected_06_dark = 2131165239;
			
			// aapt resource value: 0x7F070038
			public const int ic_mr_button_connected_06_light = 2131165240;
			
			// aapt resource value: 0x7F070039
			public const int ic_mr_button_connected_07_dark = 2131165241;
			
			// aapt resource value: 0x7F07003A
			public const int ic_mr_button_connected_07_light = 2131165242;
			
			// aapt resource value: 0x7F07003B
			public const int ic_mr_button_connected_08_dark = 2131165243;
			
			// aapt resource value: 0x7F07003C
			public const int ic_mr_button_connected_08_light = 2131165244;
			
			// aapt resource value: 0x7F07003D
			public const int ic_mr_button_connected_09_dark = 2131165245;
			
			// aapt resource value: 0x7F07003E
			public const int ic_mr_button_connected_09_light = 2131165246;
			
			// aapt resource value: 0x7F07003F
			public const int ic_mr_button_connected_10_dark = 2131165247;
			
			// aapt resource value: 0x7F070040
			public const int ic_mr_button_connected_10_light = 2131165248;
			
			// aapt resource value: 0x7F070041
			public const int ic_mr_button_connected_11_dark = 2131165249;
			
			// aapt resource value: 0x7F070042
			public const int ic_mr_button_connected_11_light = 2131165250;
			
			// aapt resource value: 0x7F070043
			public const int ic_mr_button_connected_12_dark = 2131165251;
			
			// aapt resource value: 0x7F070044
			public const int ic_mr_button_connected_12_light = 2131165252;
			
			// aapt resource value: 0x7F070045
			public const int ic_mr_button_connected_13_dark = 2131165253;
			
			// aapt resource value: 0x7F070046
			public const int ic_mr_button_connected_13_light = 2131165254;
			
			// aapt resource value: 0x7F070047
			public const int ic_mr_button_connected_14_dark = 2131165255;
			
			// aapt resource value: 0x7F070048
			public const int ic_mr_button_connected_14_light = 2131165256;
			
			// aapt resource value: 0x7F070049
			public const int ic_mr_button_connected_15_dark = 2131165257;
			
			// aapt resource value: 0x7F07004A
			public const int ic_mr_button_connected_15_light = 2131165258;
			
			// aapt resource value: 0x7F07004B
			public const int ic_mr_button_connected_16_dark = 2131165259;
			
			// aapt resource value: 0x7F07004C
			public const int ic_mr_button_connected_16_light = 2131165260;
			
			// aapt resource value: 0x7F07004D
			public const int ic_mr_button_connected_17_dark = 2131165261;
			
			// aapt resource value: 0x7F07004E
			public const int ic_mr_button_connected_17_light = 2131165262;
			
			// aapt resource value: 0x7F07004F
			public const int ic_mr_button_connected_18_dark = 2131165263;
			
			// aapt resource value: 0x7F070050
			public const int ic_mr_button_connected_18_light = 2131165264;
			
			// aapt resource value: 0x7F070051
			public const int ic_mr_button_connected_19_dark = 2131165265;
			
			// aapt resource value: 0x7F070052
			public const int ic_mr_button_connected_19_light = 2131165266;
			
			// aapt resource value: 0x7F070053
			public const int ic_mr_button_connected_20_dark = 2131165267;
			
			// aapt resource value: 0x7F070054
			public const int ic_mr_button_connected_20_light = 2131165268;
			
			// aapt resource value: 0x7F070055
			public const int ic_mr_button_connected_21_dark = 2131165269;
			
			// aapt resource value: 0x7F070056
			public const int ic_mr_button_connected_21_light = 2131165270;
			
			// aapt resource value: 0x7F070057
			public const int ic_mr_button_connected_22_dark = 2131165271;
			
			// aapt resource value: 0x7F070058
			public const int ic_mr_button_connected_22_light = 2131165272;
			
			// aapt resource value: 0x7F070059
			public const int ic_mr_button_connected_23_dark = 2131165273;
			
			// aapt resource value: 0x7F07005A
			public const int ic_mr_button_connected_23_light = 2131165274;
			
			// aapt resource value: 0x7F07005B
			public const int ic_mr_button_connected_24_dark = 2131165275;
			
			// aapt resource value: 0x7F07005C
			public const int ic_mr_button_connected_24_light = 2131165276;
			
			// aapt resource value: 0x7F07005D
			public const int ic_mr_button_connected_25_dark = 2131165277;
			
			// aapt resource value: 0x7F07005E
			public const int ic_mr_button_connected_25_light = 2131165278;
			
			// aapt resource value: 0x7F07005F
			public const int ic_mr_button_connected_26_dark = 2131165279;
			
			// aapt resource value: 0x7F070060
			public const int ic_mr_button_connected_26_light = 2131165280;
			
			// aapt resource value: 0x7F070061
			public const int ic_mr_button_connected_27_dark = 2131165281;
			
			// aapt resource value: 0x7F070062
			public const int ic_mr_button_connected_27_light = 2131165282;
			
			// aapt resource value: 0x7F070063
			public const int ic_mr_button_connected_28_dark = 2131165283;
			
			// aapt resource value: 0x7F070064
			public const int ic_mr_button_connected_28_light = 2131165284;
			
			// aapt resource value: 0x7F070065
			public const int ic_mr_button_connected_29_dark = 2131165285;
			
			// aapt resource value: 0x7F070066
			public const int ic_mr_button_connected_29_light = 2131165286;
			
			// aapt resource value: 0x7F070067
			public const int ic_mr_button_connected_30_dark = 2131165287;
			
			// aapt resource value: 0x7F070068
			public const int ic_mr_button_connected_30_light = 2131165288;
			
			// aapt resource value: 0x7F070069
			public const int ic_mr_button_connecting_00_dark = 2131165289;
			
			// aapt resource value: 0x7F07006A
			public const int ic_mr_button_connecting_00_light = 2131165290;
			
			// aapt resource value: 0x7F07006B
			public const int ic_mr_button_connecting_01_dark = 2131165291;
			
			// aapt resource value: 0x7F07006C
			public const int ic_mr_button_connecting_01_light = 2131165292;
			
			// aapt resource value: 0x7F07006D
			public const int ic_mr_button_connecting_02_dark = 2131165293;
			
			// aapt resource value: 0x7F07006E
			public const int ic_mr_button_connecting_02_light = 2131165294;
			
			// aapt resource value: 0x7F07006F
			public const int ic_mr_button_connecting_03_dark = 2131165295;
			
			// aapt resource value: 0x7F070070
			public const int ic_mr_button_connecting_03_light = 2131165296;
			
			// aapt resource value: 0x7F070071
			public const int ic_mr_button_connecting_04_dark = 2131165297;
			
			// aapt resource value: 0x7F070072
			public const int ic_mr_button_connecting_04_light = 2131165298;
			
			// aapt resource value: 0x7F070073
			public const int ic_mr_button_connecting_05_dark = 2131165299;
			
			// aapt resource value: 0x7F070074
			public const int ic_mr_button_connecting_05_light = 2131165300;
			
			// aapt resource value: 0x7F070075
			public const int ic_mr_button_connecting_06_dark = 2131165301;
			
			// aapt resource value: 0x7F070076
			public const int ic_mr_button_connecting_06_light = 2131165302;
			
			// aapt resource value: 0x7F070077
			public const int ic_mr_button_connecting_07_dark = 2131165303;
			
			// aapt resource value: 0x7F070078
			public const int ic_mr_button_connecting_07_light = 2131165304;
			
			// aapt resource value: 0x7F070079
			public const int ic_mr_button_connecting_08_dark = 2131165305;
			
			// aapt resource value: 0x7F07007A
			public const int ic_mr_button_connecting_08_light = 2131165306;
			
			// aapt resource value: 0x7F07007B
			public const int ic_mr_button_connecting_09_dark = 2131165307;
			
			// aapt resource value: 0x7F07007C
			public const int ic_mr_button_connecting_09_light = 2131165308;
			
			// aapt resource value: 0x7F07007D
			public const int ic_mr_button_connecting_10_dark = 2131165309;
			
			// aapt resource value: 0x7F07007E
			public const int ic_mr_button_connecting_10_light = 2131165310;
			
			// aapt resource value: 0x7F07007F
			public const int ic_mr_button_connecting_11_dark = 2131165311;
			
			// aapt resource value: 0x7F070080
			public const int ic_mr_button_connecting_11_light = 2131165312;
			
			// aapt resource value: 0x7F070081
			public const int ic_mr_button_connecting_12_dark = 2131165313;
			
			// aapt resource value: 0x7F070082
			public const int ic_mr_button_connecting_12_light = 2131165314;
			
			// aapt resource value: 0x7F070083
			public const int ic_mr_button_connecting_13_dark = 2131165315;
			
			// aapt resource value: 0x7F070084
			public const int ic_mr_button_connecting_13_light = 2131165316;
			
			// aapt resource value: 0x7F070085
			public const int ic_mr_button_connecting_14_dark = 2131165317;
			
			// aapt resource value: 0x7F070086
			public const int ic_mr_button_connecting_14_light = 2131165318;
			
			// aapt resource value: 0x7F070087
			public const int ic_mr_button_connecting_15_dark = 2131165319;
			
			// aapt resource value: 0x7F070088
			public const int ic_mr_button_connecting_15_light = 2131165320;
			
			// aapt resource value: 0x7F070089
			public const int ic_mr_button_connecting_16_dark = 2131165321;
			
			// aapt resource value: 0x7F07008A
			public const int ic_mr_button_connecting_16_light = 2131165322;
			
			// aapt resource value: 0x7F07008B
			public const int ic_mr_button_connecting_17_dark = 2131165323;
			
			// aapt resource value: 0x7F07008C
			public const int ic_mr_button_connecting_17_light = 2131165324;
			
			// aapt resource value: 0x7F07008D
			public const int ic_mr_button_connecting_18_dark = 2131165325;
			
			// aapt resource value: 0x7F07008E
			public const int ic_mr_button_connecting_18_light = 2131165326;
			
			// aapt resource value: 0x7F07008F
			public const int ic_mr_button_connecting_19_dark = 2131165327;
			
			// aapt resource value: 0x7F070090
			public const int ic_mr_button_connecting_19_light = 2131165328;
			
			// aapt resource value: 0x7F070091
			public const int ic_mr_button_connecting_20_dark = 2131165329;
			
			// aapt resource value: 0x7F070092
			public const int ic_mr_button_connecting_20_light = 2131165330;
			
			// aapt resource value: 0x7F070093
			public const int ic_mr_button_connecting_21_dark = 2131165331;
			
			// aapt resource value: 0x7F070094
			public const int ic_mr_button_connecting_21_light = 2131165332;
			
			// aapt resource value: 0x7F070095
			public const int ic_mr_button_connecting_22_dark = 2131165333;
			
			// aapt resource value: 0x7F070096
			public const int ic_mr_button_connecting_22_light = 2131165334;
			
			// aapt resource value: 0x7F070097
			public const int ic_mr_button_connecting_23_dark = 2131165335;
			
			// aapt resource value: 0x7F070098
			public const int ic_mr_button_connecting_23_light = 2131165336;
			
			// aapt resource value: 0x7F070099
			public const int ic_mr_button_connecting_24_dark = 2131165337;
			
			// aapt resource value: 0x7F07009A
			public const int ic_mr_button_connecting_24_light = 2131165338;
			
			// aapt resource value: 0x7F07009B
			public const int ic_mr_button_connecting_25_dark = 2131165339;
			
			// aapt resource value: 0x7F07009C
			public const int ic_mr_button_connecting_25_light = 2131165340;
			
			// aapt resource value: 0x7F07009D
			public const int ic_mr_button_connecting_26_dark = 2131165341;
			
			// aapt resource value: 0x7F07009E
			public const int ic_mr_button_connecting_26_light = 2131165342;
			
			// aapt resource value: 0x7F07009F
			public const int ic_mr_button_connecting_27_dark = 2131165343;
			
			// aapt resource value: 0x7F0700A0
			public const int ic_mr_button_connecting_27_light = 2131165344;
			
			// aapt resource value: 0x7F0700A1
			public const int ic_mr_button_connecting_28_dark = 2131165345;
			
			// aapt resource value: 0x7F0700A2
			public const int ic_mr_button_connecting_28_light = 2131165346;
			
			// aapt resource value: 0x7F0700A3
			public const int ic_mr_button_connecting_29_dark = 2131165347;
			
			// aapt resource value: 0x7F0700A4
			public const int ic_mr_button_connecting_29_light = 2131165348;
			
			// aapt resource value: 0x7F0700A5
			public const int ic_mr_button_connecting_30_dark = 2131165349;
			
			// aapt resource value: 0x7F0700A6
			public const int ic_mr_button_connecting_30_light = 2131165350;
			
			// aapt resource value: 0x7F0700A7
			public const int ic_mr_button_disabled_dark = 2131165351;
			
			// aapt resource value: 0x7F0700A8
			public const int ic_mr_button_disabled_light = 2131165352;
			
			// aapt resource value: 0x7F0700A9
			public const int ic_mr_button_disconnected_dark = 2131165353;
			
			// aapt resource value: 0x7F0700AA
			public const int ic_mr_button_disconnected_light = 2131165354;
			
			// aapt resource value: 0x7F0700AB
			public const int ic_mr_button_grey = 2131165355;
			
			// aapt resource value: 0x7F0700AC
			public const int ic_unchecked_checkbox = 2131165356;
			
			// aapt resource value: 0x7F0700AD
			public const int ic_vol_mute = 2131165357;
			
			// aapt resource value: 0x7F0700AE
			public const int ic_vol_type_speaker_dark = 2131165358;
			
			// aapt resource value: 0x7F0700AF
			public const int ic_vol_type_speaker_group_dark = 2131165359;
			
			// aapt resource value: 0x7F0700B0
			public const int ic_vol_type_speaker_group_light = 2131165360;
			
			// aapt resource value: 0x7F0700B1
			public const int ic_vol_type_speaker_light = 2131165361;
			
			// aapt resource value: 0x7F0700B2
			public const int ic_vol_type_tv_dark = 2131165362;
			
			// aapt resource value: 0x7F0700B3
			public const int ic_vol_type_tv_light = 2131165363;
			
			// aapt resource value: 0x7F0700B4
			public const int ic_vol_unmute = 2131165364;
			
			// aapt resource value: 0x7F0700B5
			public const int mr_button_connected_dark = 2131165365;
			
			// aapt resource value: 0x7F0700B6
			public const int mr_button_connected_light = 2131165366;
			
			// aapt resource value: 0x7F0700B7
			public const int mr_button_connecting_dark = 2131165367;
			
			// aapt resource value: 0x7F0700B8
			public const int mr_button_connecting_light = 2131165368;
			
			// aapt resource value: 0x7F0700B9
			public const int mr_button_dark = 2131165369;
			
			// aapt resource value: 0x7F0700BA
			public const int mr_button_dark_static = 2131165370;
			
			// aapt resource value: 0x7F0700BB
			public const int mr_button_light = 2131165371;
			
			// aapt resource value: 0x7F0700BC
			public const int mr_button_light_static = 2131165372;
			
			// aapt resource value: 0x7F0700BD
			public const int mr_cast_checkbox = 2131165373;
			
			// aapt resource value: 0x7F0700BE
			public const int mr_cast_group_seekbar_track = 2131165374;
			
			// aapt resource value: 0x7F0700BF
			public const int mr_cast_mute_button = 2131165375;
			
			// aapt resource value: 0x7F0700C0
			public const int mr_cast_route_seekbar_track = 2131165376;
			
			// aapt resource value: 0x7F0700C1
			public const int mr_cast_stop = 2131165377;
			
			// aapt resource value: 0x7F0700C2
			public const int mr_cast_thumb = 2131165378;
			
			// aapt resource value: 0x7F0700C3
			public const int mr_dialog_close_dark = 2131165379;
			
			// aapt resource value: 0x7F0700C4
			public const int mr_dialog_close_light = 2131165380;
			
			// aapt resource value: 0x7F0700C5
			public const int mr_dialog_material_background_dark = 2131165381;
			
			// aapt resource value: 0x7F0700C6
			public const int mr_dialog_material_background_light = 2131165382;
			
			// aapt resource value: 0x7F0700C7
			public const int mr_group_collapse = 2131165383;
			
			// aapt resource value: 0x7F0700C8
			public const int mr_group_expand = 2131165384;
			
			// aapt resource value: 0x7F0700C9
			public const int mr_media_pause_dark = 2131165385;
			
			// aapt resource value: 0x7F0700CA
			public const int mr_media_pause_light = 2131165386;
			
			// aapt resource value: 0x7F0700CB
			public const int mr_media_play_dark = 2131165387;
			
			// aapt resource value: 0x7F0700CC
			public const int mr_media_play_light = 2131165388;
			
			// aapt resource value: 0x7F0700CD
			public const int mr_media_stop_dark = 2131165389;
			
			// aapt resource value: 0x7F0700CE
			public const int mr_media_stop_light = 2131165390;
			
			// aapt resource value: 0x7F0700CF
			public const int mr_vol_type_audiotrack_dark = 2131165391;
			
			// aapt resource value: 0x7F0700D0
			public const int mr_vol_type_audiotrack_light = 2131165392;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F080000
			public const int action0 = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int action_divider = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int background = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int browser_actions_header_text = 2131230723;
			
			// aapt resource value: 0x7F080006
			public const int browser_actions_menu_items = 2131230726;
			
			// aapt resource value: 0x7F080004
			public const int browser_actions_menu_item_icon = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int browser_actions_menu_item_text = 2131230725;
			
			// aapt resource value: 0x7F080007
			public const int browser_actions_menu_view = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int cancel_action = 2131230728;
			
			// aapt resource value: 0x7F080009
			public const int chronometer = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public const int empty = 2131230730;
			
			// aapt resource value: 0x7F08000B
			public const int end_padder = 2131230731;
			
			// aapt resource value: 0x7F08000C
			public const int icon = 2131230732;
			
			// aapt resource value: 0x7F08000D
			public const int info = 2131230733;
			
			// aapt resource value: 0x7F08000E
			public const int line1 = 2131230734;
			
			// aapt resource value: 0x7F08000F
			public const int line3 = 2131230735;
			
			// aapt resource value: 0x7F080010
			public const int media_actions = 2131230736;
			
			// aapt resource value: 0x7F080011
			public const int media_controller_compat_view_tag = 2131230737;
			
			// aapt resource value: 0x7F080012
			public const int mr_art = 2131230738;
			
			// aapt resource value: 0x7F080013
			public const int mr_cast_checkbox = 2131230739;
			
			// aapt resource value: 0x7F080014
			public const int mr_cast_close_button = 2131230740;
			
			// aapt resource value: 0x7F080015
			public const int mr_cast_divider = 2131230741;
			
			// aapt resource value: 0x7F080016
			public const int mr_cast_group_icon = 2131230742;
			
			// aapt resource value: 0x7F080017
			public const int mr_cast_group_name = 2131230743;
			
			// aapt resource value: 0x7F080018
			public const int mr_cast_group_progress_bar = 2131230744;
			
			// aapt resource value: 0x7F080019
			public const int mr_cast_header_name = 2131230745;
			
			// aapt resource value: 0x7F08001A
			public const int mr_cast_list = 2131230746;
			
			// aapt resource value: 0x7F08001B
			public const int mr_cast_meta_art = 2131230747;
			
			// aapt resource value: 0x7F08001C
			public const int mr_cast_meta_background = 2131230748;
			
			// aapt resource value: 0x7F08001D
			public const int mr_cast_meta_black_scrim = 2131230749;
			
			// aapt resource value: 0x7F08001E
			public const int mr_cast_meta_subtitle = 2131230750;
			
			// aapt resource value: 0x7F08001F
			public const int mr_cast_meta_title = 2131230751;
			
			// aapt resource value: 0x7F080020
			public const int mr_cast_mute_button = 2131230752;
			
			// aapt resource value: 0x7F080021
			public const int mr_cast_route_icon = 2131230753;
			
			// aapt resource value: 0x7F080022
			public const int mr_cast_route_name = 2131230754;
			
			// aapt resource value: 0x7F080023
			public const int mr_cast_route_progress_bar = 2131230755;
			
			// aapt resource value: 0x7F080024
			public const int mr_cast_stop_button = 2131230756;
			
			// aapt resource value: 0x7F080025
			public const int mr_cast_volume_layout = 2131230757;
			
			// aapt resource value: 0x7F080026
			public const int mr_cast_volume_slider = 2131230758;
			
			// aapt resource value: 0x7F080027
			public const int mr_chooser_list = 2131230759;
			
			// aapt resource value: 0x7F080028
			public const int mr_chooser_route_desc = 2131230760;
			
			// aapt resource value: 0x7F080029
			public const int mr_chooser_route_icon = 2131230761;
			
			// aapt resource value: 0x7F08002A
			public const int mr_chooser_route_name = 2131230762;
			
			// aapt resource value: 0x7F08002B
			public const int mr_chooser_route_progress_bar = 2131230763;
			
			// aapt resource value: 0x7F08002C
			public const int mr_chooser_title = 2131230764;
			
			// aapt resource value: 0x7F08002D
			public const int mr_close = 2131230765;
			
			// aapt resource value: 0x7F08002E
			public const int mr_control_divider = 2131230766;
			
			// aapt resource value: 0x7F08002F
			public const int mr_control_playback_ctrl = 2131230767;
			
			// aapt resource value: 0x7F080030
			public const int mr_control_subtitle = 2131230768;
			
			// aapt resource value: 0x7F080031
			public const int mr_control_title = 2131230769;
			
			// aapt resource value: 0x7F080032
			public const int mr_control_title_container = 2131230770;
			
			// aapt resource value: 0x7F080033
			public const int mr_custom_control = 2131230771;
			
			// aapt resource value: 0x7F080034
			public const int mr_default_control = 2131230772;
			
			// aapt resource value: 0x7F080035
			public const int mr_dialog_area = 2131230773;
			
			// aapt resource value: 0x7F080036
			public const int mr_expandable_area = 2131230774;
			
			// aapt resource value: 0x7F080037
			public const int mr_group_expand_collapse = 2131230775;
			
			// aapt resource value: 0x7F080038
			public const int mr_group_volume_route_name = 2131230776;
			
			// aapt resource value: 0x7F080039
			public const int mr_media_main_control = 2131230777;
			
			// aapt resource value: 0x7F08003A
			public const int mr_name = 2131230778;
			
			// aapt resource value: 0x7F08003B
			public const int mr_picker_close_button = 2131230779;
			
			// aapt resource value: 0x7F08003C
			public const int mr_picker_header_name = 2131230780;
			
			// aapt resource value: 0x7F08003D
			public const int mr_picker_list = 2131230781;
			
			// aapt resource value: 0x7F08003E
			public const int mr_picker_route_icon = 2131230782;
			
			// aapt resource value: 0x7F08003F
			public const int mr_picker_route_name = 2131230783;
			
			// aapt resource value: 0x7F080040
			public const int mr_picker_route_progress_bar = 2131230784;
			
			// aapt resource value: 0x7F080041
			public const int mr_playback_control = 2131230785;
			
			// aapt resource value: 0x7F080042
			public const int mr_title_bar = 2131230786;
			
			// aapt resource value: 0x7F080043
			public const int mr_volume_control = 2131230787;
			
			// aapt resource value: 0x7F080044
			public const int mr_volume_group_list = 2131230788;
			
			// aapt resource value: 0x7F080045
			public const int mr_volume_item_icon = 2131230789;
			
			// aapt resource value: 0x7F080046
			public const int mr_volume_slider = 2131230790;
			
			// aapt resource value: 0x7F080047
			public const int nav_controller_view_tag = 2131230791;
			
			// aapt resource value: 0x7F080048
			public const int notification_main_column = 2131230792;
			
			// aapt resource value: 0x7F080049
			public const int notification_main_column_container = 2131230793;
			
			// aapt resource value: 0x7F08004A
			public const int progress = 2131230794;
			
			// aapt resource value: 0x7F08004B
			public const int right_side = 2131230795;
			
			// aapt resource value: 0x7F08004C
			public const int sliding_tabs = 2131230796;
			
			// aapt resource value: 0x7F08004D
			public const int status_bar_latest_event_content = 2131230797;
			
			// aapt resource value: 0x7F08004E
			public const int text = 2131230798;
			
			// aapt resource value: 0x7F08004F
			public const int text2 = 2131230799;
			
			// aapt resource value: 0x7F080050
			public const int time = 2131230800;
			
			// aapt resource value: 0x7F080051
			public const int title = 2131230801;
			
			// aapt resource value: 0x7F080052
			public const int toolbar = 2131230802;
			
			// aapt resource value: 0x7F080053
			public const int volume_item_container = 2131230803;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F090000
			public const int cancel_button_image_alpha = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int config_navAnimTime = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int mr_cast_volume_slider_layout_animation_duration_ms = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int mr_controller_volume_group_list_animation_duration_ms = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int mr_controller_volume_group_list_fade_in_duration_ms = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int mr_controller_volume_group_list_fade_out_duration_ms = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int mr_update_routes_delay_ms = 2131296262;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Interpolator
		{
			
			// aapt resource value: 0x7F0A0000
			public const int mr_fast_out_slow_in = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int mr_linear_out_slow_in = 2131361793;
			
			static Interpolator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Interpolator()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F0B0002
			public const int browser_actions_context_menu_page = 2131427330;
			
			// aapt resource value: 0x7F0B0003
			public const int browser_actions_context_menu_row = 2131427331;
			
			// aapt resource value: 0x7F0B0004
			public const int mr_cast_dialog = 2131427332;
			
			// aapt resource value: 0x7F0B0005
			public const int mr_cast_group_item = 2131427333;
			
			// aapt resource value: 0x7F0B0006
			public const int mr_cast_group_volume_item = 2131427334;
			
			// aapt resource value: 0x7F0B0007
			public const int mr_cast_header_item = 2131427335;
			
			// aapt resource value: 0x7F0B0008
			public const int mr_cast_media_metadata = 2131427336;
			
			// aapt resource value: 0x7F0B0009
			public const int mr_cast_route_item = 2131427337;
			
			// aapt resource value: 0x7F0B000A
			public const int mr_chooser_dialog = 2131427338;
			
			// aapt resource value: 0x7F0B000B
			public const int mr_chooser_list_item = 2131427339;
			
			// aapt resource value: 0x7F0B000C
			public const int mr_controller_material_dialog_b = 2131427340;
			
			// aapt resource value: 0x7F0B000D
			public const int mr_controller_volume_item = 2131427341;
			
			// aapt resource value: 0x7F0B000E
			public const int mr_picker_dialog = 2131427342;
			
			// aapt resource value: 0x7F0B000F
			public const int mr_picker_header_item = 2131427343;
			
			// aapt resource value: 0x7F0B0010
			public const int mr_picker_route_item = 2131427344;
			
			// aapt resource value: 0x7F0B0011
			public const int mr_playback_control = 2131427345;
			
			// aapt resource value: 0x7F0B0012
			public const int mr_volume_control = 2131427346;
			
			// aapt resource value: 0x7F0B0013
			public const int notification_media_action = 2131427347;
			
			// aapt resource value: 0x7F0B0014
			public const int notification_media_cancel_action = 2131427348;
			
			// aapt resource value: 0x7F0B0015
			public const int notification_template_big_media = 2131427349;
			
			// aapt resource value: 0x7F0B0016
			public const int notification_template_big_media_custom = 2131427350;
			
			// aapt resource value: 0x7F0B0017
			public const int notification_template_big_media_narrow = 2131427351;
			
			// aapt resource value: 0x7F0B0018
			public const int notification_template_big_media_narrow_custom = 2131427352;
			
			// aapt resource value: 0x7F0B0019
			public const int notification_template_lines_media = 2131427353;
			
			// aapt resource value: 0x7F0B001A
			public const int notification_template_media = 2131427354;
			
			// aapt resource value: 0x7F0B001B
			public const int notification_template_media_custom = 2131427355;
			
			// aapt resource value: 0x7F0B0000
			public const int Tabbar = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public const int Toolbar = 2131427329;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F0C0000
			public const int icon = 2131492864;
			
			// aapt resource value: 0x7F0C0001
			public const int icon_round = 2131492865;
			
			// aapt resource value: 0x7F0C0002
			public const int launcher_foreground = 2131492866;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0D0000
			public const int copy_toast_msg = 2131558400;
			
			// aapt resource value: 0x7F0D0001
			public const int fallback_menu_item_copy_link = 2131558401;
			
			// aapt resource value: 0x7F0D0002
			public const int fallback_menu_item_open_in_browser = 2131558402;
			
			// aapt resource value: 0x7F0D0003
			public const int fallback_menu_item_share_link = 2131558403;
			
			// aapt resource value: 0x7F0D0004
			public const int mr_button_content_description = 2131558404;
			
			// aapt resource value: 0x7F0D0005
			public const int mr_cast_button_connected = 2131558405;
			
			// aapt resource value: 0x7F0D0006
			public const int mr_cast_button_connecting = 2131558406;
			
			// aapt resource value: 0x7F0D0007
			public const int mr_cast_button_disconnected = 2131558407;
			
			// aapt resource value: 0x7F0D0008
			public const int mr_cast_dialog_title_view_placeholder = 2131558408;
			
			// aapt resource value: 0x7F0D0009
			public const int mr_chooser_searching = 2131558409;
			
			// aapt resource value: 0x7F0D000A
			public const int mr_chooser_title = 2131558410;
			
			// aapt resource value: 0x7F0D000B
			public const int mr_controller_album_art = 2131558411;
			
			// aapt resource value: 0x7F0D000C
			public const int mr_controller_casting_screen = 2131558412;
			
			// aapt resource value: 0x7F0D000D
			public const int mr_controller_close_description = 2131558413;
			
			// aapt resource value: 0x7F0D000E
			public const int mr_controller_collapse_group = 2131558414;
			
			// aapt resource value: 0x7F0D000F
			public const int mr_controller_disconnect = 2131558415;
			
			// aapt resource value: 0x7F0D0010
			public const int mr_controller_expand_group = 2131558416;
			
			// aapt resource value: 0x7F0D0011
			public const int mr_controller_no_info_available = 2131558417;
			
			// aapt resource value: 0x7F0D0012
			public const int mr_controller_no_media_selected = 2131558418;
			
			// aapt resource value: 0x7F0D0013
			public const int mr_controller_pause = 2131558419;
			
			// aapt resource value: 0x7F0D0014
			public const int mr_controller_play = 2131558420;
			
			// aapt resource value: 0x7F0D0015
			public const int mr_controller_stop = 2131558421;
			
			// aapt resource value: 0x7F0D0016
			public const int mr_controller_stop_casting = 2131558422;
			
			// aapt resource value: 0x7F0D0017
			public const int mr_controller_volume_slider = 2131558423;
			
			// aapt resource value: 0x7F0D0018
			public const int mr_dialog_default_group_name = 2131558424;
			
			// aapt resource value: 0x7F0D0019
			public const int mr_dialog_groupable_header = 2131558425;
			
			// aapt resource value: 0x7F0D001A
			public const int mr_dialog_transferable_header = 2131558426;
			
			// aapt resource value: 0x7F0D001B
			public const int mr_system_route_name = 2131558427;
			
			// aapt resource value: 0x7F0D001C
			public const int mr_user_route_category_name = 2131558428;
			
			// aapt resource value: 0x7F0D001D
			public const int nav_app_bar_navigate_up_description = 2131558429;
			
			// aapt resource value: 0x7F0D001E
			public const int nav_app_bar_open_drawer_description = 2131558430;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0E0000
			public const int AppCompatDialogStyle = 2131623936;
			
			// aapt resource value: 0x7F0E0001
			public const int MainTheme = 2131623937;
			
			// aapt resource value: 0x7F0E0002
			public const int MainTheme_Base = 2131623938;
			
			// aapt resource value: 0x7F0E0003
			public const int TextAppearance_Compat_Notification_Info_Media = 2131623939;
			
			// aapt resource value: 0x7F0E0004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131623940;
			
			// aapt resource value: 0x7F0E0005
			public const int TextAppearance_Compat_Notification_Media = 2131623941;
			
			// aapt resource value: 0x7F0E0006
			public const int TextAppearance_Compat_Notification_Time_Media = 2131623942;
			
			// aapt resource value: 0x7F0E0007
			public const int TextAppearance_Compat_Notification_Title_Media = 2131623943;
			
			// aapt resource value: 0x7F0E0008
			public const int TextAppearance_MediaRouter_Dynamic_Body = 2131623944;
			
			// aapt resource value: 0x7F0E0009
			public const int TextAppearance_MediaRouter_Dynamic_Body_Light = 2131623945;
			
			// aapt resource value: 0x7F0E000A
			public const int TextAppearance_MediaRouter_Dynamic_Header = 2131623946;
			
			// aapt resource value: 0x7F0E000B
			public const int TextAppearance_MediaRouter_Dynamic_Header_Light = 2131623947;
			
			// aapt resource value: 0x7F0E000C
			public const int TextAppearance_MediaRouter_Dynamic_Metadata_PrimaryText = 2131623948;
			
			// aapt resource value: 0x7F0E000D
			public const int TextAppearance_MediaRouter_Dynamic_Metadata_SecondaryText = 2131623949;
			
			// aapt resource value: 0x7F0E000E
			public const int TextAppearance_MediaRouter_PrimaryText = 2131623950;
			
			// aapt resource value: 0x7F0E000F
			public const int TextAppearance_MediaRouter_SecondaryText = 2131623951;
			
			// aapt resource value: 0x7F0E0010
			public const int TextAppearance_MediaRouter_Title = 2131623952;
			
			// aapt resource value: 0x7F0E0011
			public const int ThemeOverlay_MediaRouter_Dark = 2131623953;
			
			// aapt resource value: 0x7F0E0012
			public const int ThemeOverlay_MediaRouter_Light = 2131623954;
			
			// aapt resource value: 0x7F0E0013
			public const int Theme_MediaRouter = 2131623955;
			
			// aapt resource value: 0x7F0E0014
			public const int Theme_MediaRouter_Light = 2131623956;
			
			// aapt resource value: 0x7F0E0015
			public const int Theme_MediaRouter_LightControlPanel = 2131623957;
			
			// aapt resource value: 0x7F0E0016
			public const int Theme_MediaRouter_Light_DarkControlPanel = 2131623958;
			
			// aapt resource value: 0x7F0E0017
			public const int Widget_MediaRouter_Light_MediaRouteButton = 2131623959;
			
			// aapt resource value: 0x7F0E0018
			public const int Widget_MediaRouter_MediaRouteButton = 2131623960;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x0,0x7F030000,0x7F030001,0x7F030002,0x7F030017 }
			public static int[] ActivityNavigator = new int[] {
					0,
					2130903040,
					2130903041,
					2130903042,
					2130903063};
			
			// aapt resource value: 1
			public const int ActivityNavigator_action = 1;
			
			// aapt resource value: 0
			public const int ActivityNavigator_android_name = 0;
			
			// aapt resource value: 2
			public const int ActivityNavigator_data = 2;
			
			// aapt resource value: 3
			public const int ActivityNavigator_dataPattern = 3;
			
			// aapt resource value: 4
			public const int ActivityNavigator_targetPackage = 4;
			
			// aapt resource value: { 0x0,0x0,0x7F030003,0x7F030004,0x7F030009 }
			public static int[] MediaRouteButton = new int[] {
					0,
					0,
					2130903043,
					2130903044,
					2130903049};
			
			// aapt resource value: 0
			public const int MediaRouteButton_android_minHeight = 0;
			
			// aapt resource value: 1
			public const int MediaRouteButton_android_minWidth = 1;
			
			// aapt resource value: 2
			public const int MediaRouteButton_externalRouteEnabledDrawable = 2;
			
			// aapt resource value: 3
			public const int MediaRouteButton_externalRouteEnabledDrawableStatic = 3;
			
			// aapt resource value: 4
			public const int MediaRouteButton_mediaRouteButtonTint = 4;
			
			// aapt resource value: { 0x7F030016 }
			public static int[] NavHost = new int[] {
					2130903062};
			
			// aapt resource value: 0
			public const int NavHost_navGraph = 0;
			
			// aapt resource value: { 0x7F030005 }
			public static int[] NavInclude = new int[] {
					2130903045};
			
			// aapt resource value: 0
			public const int NavInclude_graph = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F100000
			public const int image_share_filepaths = 2131755008;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
